### ISSUE TITLE
[Fabric 1.20.1] Exception occurred in netty pipeline

### ISSUE THREAD

**Issue by whatamaniac** [XiLaiTL/Yuushya-Townscape#15]
Hello,
We're having this issue where the server doesn't let any player join after we installed the Yuushya Mod and throws Internal Exception: Connection Reset message. and the Console says this: ```[Netty Epoll Server IO #6/ERROR]: Exception occurred in netty pipeline
[Server] io.netty.handler.codec.EncoderExceptionjava.lang.IllegalArgumentException: unable to fit 2320798 into 3  
[Server] at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[netty-codec-4.1.82.Final.jar:?] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:?]
[Server] at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.82.Final.jar:?] 
[Server] at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.82.Final.jar:?]
[Server] at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.82.Final.jar:?]
[Server] at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[netty-codec-4.1.82.Final.jar:?] 
[Server] at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:?]
[Server] at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.82.Final.jar:?]
[Server] at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.82.Final.jar:?]
[Server] at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.82.Final.jar:?]
[Server] at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[netty-codec-4.1.82.Final.jar:?] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:?]
[Server] at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.82.Final.jar:?]
[Server] at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.82.Final.jar:?] 
[Server] at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.82.Final.jar:?]
[Server] at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.82.Final.jar:?] 
[Server] at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:?]
[Server] at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.82.Final.jar:?]
[Server] at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071) ~[netty-transport-4.1.82.Final.jar:?] 
[Server] at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar:?] [Server] at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.82.Final.jar:?]
[Server] at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.82.Final.jar:?]
[Server] at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[netty-transport-classes-epoll-4.1.82.Final.jar:?]
[Server] at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:?]
[Server] at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:?]
[Server] at java.lang.Thread.run(Thread.java:833) ~[?:?]
[Server] Caused byjava.lang.IllegalArgumentException: unable to fit 2320798 into 3
[Server] at net.minecraft.network.SizePrepender.encode(SizePrepender.java:18) ~[server-intermediary.jar:?]
[Server] at net.minecraft.network.SizePrepender.encode(SizePrepender.java:8) ~[server-intermediary.jar:?]
[Server] at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.82.Final.jar:?] [Server] ... more [08.06 13:57:16] [Server] [Netty Epoll Server IO #6/INFO]: Server paused. 
[Server] [Server thread/INFO]: Saving and pausing game...
[Server] [Server thread/INFO]: Saving chunks for level 'ServerLevel[SpyCraft]'/minecraft:overworld
[Server] [Server thread/INFO]: Saving chunks for level 'ServerLevel[SpyCraft]'/minecraft:the_nether
[Server] [Server thread/INFO]: Saving chunks for level 'ServerLevel[SpyCraft]'/ad_astra:venus_orbit
[Server] [Server thread/INFO]: Saving chunks for level 'ServerLevel[SpyCraft]'/minecells:prison
[Server] [Server thread/INFO]: Saving chunks for level 'ServerLevel[SpyCraft]'/minecells:insufferable_crypt
[Server] [Server thread/INFO]: Saving chunks for level 'ServerLevel[SpyCraft]'/ad_astra:glacio
[Server] [Server thread/INFO]: Saving chunks for level 'ServerLevel[SpyCraft]'/minecells:black_bridge
[Server] [Server thread/INFO]: Saving chunks for level 'ServerLevel[SpyCraft]'/ad_astra:mars_orbit
[Server] [Server thread/INFO]: Saving chunks for level 'ServerLevel[SpyCraft]'/ad_astra:moon
[Server] [Server thread/INFO]: Saving chunks for level 'ServerLevel[SpyCraft]'/deeperdarker:otherside
[Server] [Server thread/INFO]: Saving chunks for level 'ServerLevel[SpyCraft]'/ad_astra:earth_orbit
[Server] [Server thread/INFO]: Saving chunks for level 'ServerLevel[SpyCraft]'/ad_astra:mercury_orbit
[Server] [Server thread/INFO]: Saving chunks for level 'ServerLevel[SpyCraft]'/ad_astra:mars
[Server] [Server thread/INFO]: Saving chunks for level 'ServerLevel[SpyCraft]'/ad_astra:moon_orbit
[Server] [Server thread/INFO]: Saving chunks for level 'ServerLevel[SpyCraft]'/minecraft:the_end
[Server] [Server thread/INFO]: Saving chunks for level 'ServerLevel[SpyCraft]'/ad_astra:glacio_orbit
[Server] [Server thread/INFO]: Saving chunks for level 'ServerLevel[SpyCraft]'/the_bumblezone:the_bumblezone
[Server] [Server thread/INFO]: Saving chunks for level 'ServerLevel[SpyCraft]'/ad_astra:venus
[Server] [Server thread/INFO]: Saving chunks for level 'ServerLevel[SpyCraft]'/minecells:ramparts
[Server] [Server thread/INFO]: Saving chunks for level 'ServerLevel[SpyCraft]'/minecells:promenade
[Server] [Server thread/INFO]: Saving chunks for level 'ServerLevel[SpyCraft]'/ad_astra:mercury
[Server] [Server thread/INFO]: Saving chunks for level 'ServerLevel[SpyCraft]'/spellbladenext:glassocean
[Server] [Server thread/INFO]: Saving chunks for level 'ServerLevel[SpyCraft]'/ae2:spatial_storage
[Disconnect] SPYBOT_IS_LIVE has disconnected, reasonInternal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: unable to fit 2320798 into 3
[Server] [Server thread/INFO]: SPYBOT_IS_LIVE left the game```

We tried removing the mod to check if it's actually the Yuushya Mod and we are able to join Normally after removing the mod. The server doesn't crash but it doesn't let the player join as the data is too big for the client to handle. I think it has something to do with the Patchouli Guide Book Data being too big or something.. I'm not sure just assuming. We are playing on Prominence 2 rpg 2.8.6 Modpack and have this as an additional mod. Please lemme know if this can be fixed as we really loved your mod wanted to use it in our builds. I'll also attach the Client Latest.log 
[latest.log](https://github.com/user-attachments/files/15749252/latest.log)

**Comment by whatamaniac** [comment]
Helloo, I seem to have figured out what's causing this issue. Your mod seems to be incompatible with the Krypton mod. So idk if this issue is supposed to be yours or kryptons.
